settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: pretty-sweet-crypto-suite
  path: .
  commands:
    test:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    - html
    - js
    - css
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
